# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "⚡️ Teleport to your projects and run commands in an instant."
  homepage "https://github.com/arashnrim/tp"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.1/tp_0.1.1_Darwin_arm64.tar.gz"
      sha256 "bdbe3375e0ee780c0d5909965ef40a29a6a12989763d50d3affc2a32069330fa"

      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.1/tp_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "125d407894958e08fbe2944bc5b1302512005f4bd49ff7f4c8e9cf1d47a81388"

      def install
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.1/tp_0.1.1_Linux_arm64.tar.gz"
      sha256 "561b103eb01528f9827b60b665f0fc66100f590d4a42e8ed0e99656737dcb8fd"

      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.1/tp_0.1.1_Linux_x86_64.tar.gz"
      sha256 "ce484d3fdd47cb5f56ef129d98de1cc18182354ad228203772da0aa43b23313d"

      def install
        bin.install "tp"
      end
    end
  end
end
