# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "⚡️ Teleport to your projects and run commands in an instant."
  homepage "https://github.com/arashnrim/tp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.0/tp_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "d8fb21aafb94c2c5a7902da962f1c7d922bc9845b023f5f3821b2f114c8e844f"

      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.0/tp_0.1.0_Darwin_arm64.tar.gz"
      sha256 "df31a31700e2644a3d82b586a0ae99ca66e2fa9dbc324ac87b1b00eaeb4c061a"

      def install
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.0/tp_0.1.0_Linux_arm64.tar.gz"
      sha256 "38bba209800bad2227209b6cd8d9f7cec5dea2a1abc2f26d118b44d641bf3e4f"

      def install
        bin.install "tp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arashnrim/tp/releases/download/v0.1.0/tp_0.1.0_Linux_x86_64.tar.gz"
      sha256 "a990cc0164d2674bb9394d9159f5756be07535e43173c131402ddbf5dcce9d59"

      def install
        bin.install "tp"
      end
    end
  end
end
